### ISSUE TITLE
アイデア決め

### ISSUE THREAD

**Issue by fkymy** [42-crypto/polygon-hackathon#1]
## superfocus
- メガネ
- Earn要素を薄めて、NFTもらえるとか

## デジタル経済圏のvenmo
- フィード

## @cosme
- これ紹介してるけどお前らちゃんと買ってるの？

## MapleStoryの物々交換フリマ

---

**Comment by 0x4k1** [comment]
2.5 デジタル経済圏のvenmo
2.5 MapleStoryの物々交換フリマ
1 Superfocus

**Comment by fkymy** [comment]
MapleStoryの物々交換フリマ 3
ゲーマークレデンシャル 2
venmo 1

**Comment by Amigo927** [comment]
3ゲーマー向けクレデンシャル
1.5venmoフリマ
